version: "3.8"
services:
  api:
    build: ./service
    ports:
      - 8888:8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:${DATABASE_PASS}@db:5432/try-fastapi
      - JWT_KEY=${JWT_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_TOKEN_LIFESPAN_MINUTES=${JWT_TOKEN_LIFESPAN_MINUTES}
    volumes:
      - ./service:/usr/src/app/service:ro
    command: uvicorn service.__main__:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: try-fastapi
    ports:
      - 5544:5432
    volumes:
      - .data:/var/lib/postgresql/data
