FROM python:3.10-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir service
COPY . ./service
RUN rm -f ./service/requirements.txt

CMD ["uvicorn", "service.__main__:app", "--host", "0.0.0.0", "--port", "8000"]