"""post__owner_id

Revision ID: 5bb005ec46c3
Revises: a7b40d90fcea
Create Date: 2022-11-11 10:10:50.374713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bb005ec46c3'
down_revision = 'a7b40d90fcea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'post', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'owner_id')
    # ### end Alembic commands ###
