name: CI

on: 
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
    - '**.png'
    - 'LICENSE'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'
    - '**.png'
    - 'LICENSE'

jobs:

  try-build-docker-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: pip install poetry
    - run: cp .example.env .env
    - run: make docker-build

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Poetry
      run: |
        pip install poetry
        poetry install
    - run: cp .example.env .env
    - run: docker-compose up -d db
    - run: poetry run pytest
